"""
Report generation: PDF and CSV exports for sleep sessions.
Uses ReportLab for PDF generation.

DISCLAIMER: Reports are for research/wellness purposes only.
Not for medical diagnosis or clinical sleep staging.
"""
from __future__ import annotations
import csv
import io
from datetime import datetime
from typing import Dict, Any, Optional, List

DISCLAIMER = (
    "IMPORTANT DISCLAIMER: This report is generated by an experimental research and wellness "
    "system. Measurements, derived metrics, and the Experimental Sleep Score are NOT intended "
    "for medical diagnosis, clinical sleep staging, treatment decisions, or as a substitute for "
    "professional medical advice. Consult a qualified healthcare professional for any health concerns."
)


def _fmt_seconds(s: Optional[float]) -> str:
    if s is None:
        return "N/A"
    h = int(s // 3600)
    m = int((s % 3600) // 60)
    sec = int(s % 60)
    return f"{h:02d}:{m:02d}:{sec:02d}"


def generate_pdf_report(session: Dict[str, Any]) -> bytes:
    """Generate a PDF sleep report using ReportLab."""
    from reportlab.lib.pagesizes import A4
    from reportlab.lib import colors
    from reportlab.lib.units import cm
    from reportlab.platypus import (
        SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
    )
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.enums import TA_CENTER, TA_LEFT

    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, topMargin=2*cm, bottomMargin=2*cm,
                             leftMargin=2*cm, rightMargin=2*cm)

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle("title", parent=styles["Title"], fontSize=22,
                                  spaceAfter=6, textColor=colors.HexColor("#1e3a5f"))
    heading_style = ParagraphStyle("heading", parent=styles["Heading2"], fontSize=13,
                                    spaceAfter=4, textColor=colors.HexColor("#2563eb"))
    body_style = styles["Normal"]
    disclaimer_style = ParagraphStyle("disclaimer", parent=styles["Normal"],
                                       fontSize=8, textColor=colors.HexColor("#dc2626"),
                                       backColor=colors.HexColor("#fef2f2"),
                                       borderPad=8, leading=12)

    story = []

    # Title
    story.append(Paragraph("Smart Pillow — Sleep Report", title_style))
    story.append(Paragraph("Experimental Wellness Research System", body_style))
    story.append(Spacer(1, 0.5*cm))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#2563eb")))
    story.append(Spacer(1, 0.3*cm))

    # Disclaimer
    story.append(Paragraph(DISCLAIMER, disclaimer_style))
    story.append(Spacer(1, 0.5*cm))

    # Session Overview
    metrics = session.get("metrics") or {}
    story.append(Paragraph("Session Overview", heading_style))
    overview_data = [
        ["Session ID", str(session.get("id", "—"))],
        ["Date", session.get("start_time", "—")[:10] if session.get("start_time") else "—"],
        ["Start Time", session.get("start_time", "—")[11:19] if session.get("start_time") else "—"],
        ["End Time", session.get("end_time", "—")[11:19] if session.get("end_time") else "—"],
        ["Duration", _fmt_seconds(session.get("duration_seconds"))],
        ["Dominant Position", session.get("dominant_position", "—")],
        ["Experimental Sleep Score", f"{session.get('sleep_score', 0):.1f} / 100"],
        ["Total Samples", str(metrics.get("sample_count", "—"))],
        ["Movement Events", str(metrics.get("movement_event_count", "—"))],
    ]
    t = Table(overview_data, colWidths=[5*cm, 11*cm])
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#eff6ff")),
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("ROWBACKGROUNDS", (0, 0), (-1, -1), [colors.white, colors.HexColor("#f8fafc")]),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
        ("PADDING", (0, 0), (-1, -1), 6),
    ]))
    story.append(t)
    story.append(Spacer(1, 0.5*cm))

    # Position Breakdown
    pos_breakdown = metrics.get("position_breakdown", {})
    if pos_breakdown:
        story.append(Paragraph("Position Breakdown", heading_style))
        pos_data = [["Position", "Occurrences"]] + [
            [k, str(v)] for k, v in pos_breakdown.items()
        ]
        pt = Table(pos_data, colWidths=[8*cm, 8*cm])
        pt.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#2563eb")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 10),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f8fafc")]),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
            ("PADDING", (0, 0), (-1, -1), 6),
        ]))
        story.append(pt)
        story.append(Spacer(1, 0.5*cm))

    # Score breakdown
    score_breakdown = metrics.get("score_breakdown", {})
    if score_breakdown:
        story.append(Paragraph("Experimental Sleep Score Breakdown", heading_style))
        story.append(Paragraph(
            "Note: The weighting is an experimental project-defined heuristic and has not been clinically validated.",
            disclaimer_style
        ))
        story.append(Spacer(1, 0.2*cm))
        sb_data = [["Component", "Score (0-100)"]] + [
            [k.replace("_", " ").title(), f"{v:.1f}"] for k, v in score_breakdown.items()
        ]
        st = Table(sb_data, colWidths=[10*cm, 6*cm])
        st.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1e40af")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 10),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f8fafc")]),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
            ("PADDING", (0, 0), (-1, -1), 6),
        ]))
        story.append(st)
        story.append(Spacer(1, 0.5*cm))

    # Position Timeline
    position_events = session.get("position_events", [])
    if position_events:
        story.append(Paragraph("Position Timeline", heading_style))
        pe_data = [["Time", "Position", "Confidence", "Classifier"]] + [
            [
                pe["timestamp"][11:19] if pe.get("timestamp") else "—",
                pe.get("position", "—"),
                f"{pe.get('confidence', 0):.2f}",
                pe.get("classifier_type", "—"),
            ]
            for pe in position_events[:50]
        ]
        pet = Table(pe_data, colWidths=[4*cm, 4*cm, 4*cm, 4*cm])
        pet.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0f766e")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 9),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f0fdfa")]),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
            ("PADDING", (0, 0), (-1, -1), 5),
        ]))
        story.append(pet)
        story.append(Spacer(1, 0.5*cm))

    # Footer
    story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#94a3b8")))
    story.append(Spacer(1, 0.2*cm))
    story.append(Paragraph(
        f"Generated by Smart Pillow Research System — {datetime.utcnow().strftime('%Y-%m-%d %H:%M')} UTC",
        ParagraphStyle("footer", parent=styles["Normal"], fontSize=8,
                        textColor=colors.HexColor("#94a3b8"), alignment=TA_CENTER)
    ))

    doc.build(story)
    return buf.getvalue()


def generate_csv_report(session: Dict[str, Any]) -> str:
    """Generate a CSV report with session data."""
    output = io.StringIO()
    writer = csv.writer(output)

    # Header
    writer.writerow(["Smart Pillow Sleep Report"])
    writer.writerow([DISCLAIMER])
    writer.writerow([])

    # Overview
    metrics = session.get("metrics") or {}
    writer.writerow(["Session Overview"])
    writer.writerow(["Field", "Value"])
    writer.writerow(["Session ID", session.get("id", "")])
    writer.writerow(["Session UUID", session.get("session_uuid", "")])
    writer.writerow(["Start Time", session.get("start_time", "")])
    writer.writerow(["End Time", session.get("end_time", "")])
    writer.writerow(["Duration (seconds)", session.get("duration_seconds", "")])
    writer.writerow(["Dominant Position", session.get("dominant_position", "")])
    writer.writerow(["Experimental Sleep Score", session.get("sleep_score", "")])
    writer.writerow(["Movement Events", metrics.get("movement_event_count", "")])
    writer.writerow([])

    # Position events
    writer.writerow(["Position Events"])
    writer.writerow(["Timestamp", "Position", "Confidence", "Classifier Type"])
    for pe in session.get("position_events", []):
        writer.writerow([
            pe.get("timestamp", ""),
            pe.get("position", ""),
            pe.get("confidence", ""),
            pe.get("classifier_type", ""),
        ])
    writer.writerow([])

    # Movement events
    writer.writerow(["Movement Events"])
    writer.writerow(["Timestamp", "Level", "Accel Magnitude"])
    for me in session.get("movement_events", []):
        writer.writerow([
            me.get("timestamp", ""),
            me.get("level", ""),
            me.get("accel_magnitude", ""),
        ])
    writer.writerow([])

    # EEG metrics
    if session.get("eeg_metrics"):
        writer.writerow(["EEG Metrics (Experimental)"])
        writer.writerow(["Timestamp", "Delta", "Theta", "Alpha", "Beta", "Signal Quality"])
        for eq in session["eeg_metrics"]:
            writer.writerow([
                eq.get("timestamp", ""),
                eq.get("delta", ""),
                eq.get("theta", ""),
                eq.get("alpha", ""),
                eq.get("beta", ""),
                eq.get("signal_quality", ""),
            ])

    return output.getvalue()
